site_name: GSMc

site_author: Jane Lees, Vladimir Mikryukov
site_description: GSMc - The Global Soil Mycobiome consortium
copyright: "Copyright © 2023 GSMc. All rights reserved."

site_url:  https://GSMc-Fungi.github.io/
repo_url:  https://github.com/GSMc-Fungi/GSMc-Fungi.github.io
repo_name: "GSMc-Fungi/GSMc-Fungi.github.io"

theme:
  name: material
  # custom_dir: material # to override landing page
  palette:               # https://www.materialpalette.com/colors
    - scheme: default
      primary: indigo
      accent:  indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent:  teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  favicon: assets/favicon.ico
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - header.autohide
    - content.action.edit
    - content.code.annotate

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - toc:
      permalink: True
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - 'About':         'index.md'
  - 'Publications':  'publications.md'
  - 'Projects':      'projects.md'
